### ISSUE TITLE
Is this module discontinued?

### ISSUE THREAD

**Issue by sebfek** [bjyoungblood/BjyAuthorize#306]
Have you any suggestion for another Auth module for zf2/3?

**Comment by Ocramius** [comment]
Not discontinued, but it is stable enough to not need active maintenance
atm.

**Comment by mauriciopiber** [comment]
excuse me, it will be upgraded to ZF3?

**Comment by Ocramius** [comment]
Send a patch that moves it to 3.x compatibility (2.x compat not necessarily to be retained), and then we can tag 2.0.0

**Comment by mauriciopiber** [comment]
I will take a few days to take time, including the fact that I need to learn how to migrate and still am busy these days.

There is one way, or someone who has availability to upgrade module for ZF3? Someone proposes to take responsibility in the update?

At the moment is that, in the future is inevitable, I plan to use the module in ZF3 and I can blame me, but not today, yet.

BjyAuthorize was one of the first modules I used to learn ZF2, good example, because it was created using good practice and everything, thought of using it to learn ZF3 too.

Someone proposes?

**Comment by Ocramius** [comment]
> thought of using it to learn ZF3 too.

Note that ZF3 is no different: mostly cleanups and removal of some quirks from ZF2 :-)

**Comment by robob4him** [comment]
@Ocramius could you then take a look at PR 311?

**Comment by neilime** [comment]
@Ocramius, the last stable version "1.4.0" was created 3 years ago, more than 100 commits have been made since this version, can you create a new release that includes thes changes, so we can use your project as a stable dependency, up to date.

Thank you

**Comment by driehle** [comment]
Is it probably discontinued by now?

**Comment by barry1955** [comment]
I am having a issue upgrading components in my app.
Due to other packages requirements, I need to have zend-mvc 3.1.0 but then this breaks the bjyAuthorize dependency on zend-mvc 2.1. 
event-manager has the same issue.
event-manager has the same issue.
I need to upgrade these packages

`     - bjyoungblood/bjy-authorize 1.4.0 requires zendframework/zend-mvc ~2.1 -> satisfiable by zendframework/zend-mvc[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.1, 2.2.10, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.4.0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0rc5, 2.4.0rc6, 2.4.0rc7, 2.4.1, 2.4.10, 2.4.11, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9, 2.5.0, 2.5.1, 2.5.2, 2.5.3, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.7.0, 2.7.1, 2.7.10, 2.7.11, 2.7.12, 2.7.2, 2.7.3, 2.7.4, 2.7.5, 2.7.6, 2.7.7, 2.7.8, 2.7.9] but these conflict with your requirements or minimum-stability.
    - bjyoungblood/bjy-authorize 1.4.0 requires zendframework/zend-eventmanager ~2.1 -> satisfiable by zendframework/zend-eventmanager[2.1.0, 2.1.1, 2.1.2, 2.1.3, 2.1.4, 2.1.5, 2.1.6, 2.2.0, 2.2.0rc1, 2.2.0rc2, 2.2.0rc3, 2.2.1, 2.2.10, 2.2.2, 2.2.3, 2.2.4, 2.2.5, 2.2.6, 2.2.7, 2.2.8, 2.2.9, 2.3.0, 2.3.1, 2.3.2, 2.3.3, 2.3.4, 2.3.5, 2.3.6, 2.3.7, 2.3.8, 2.3.9, 2.4.0, 2.4.0rc1, 2.4.0rc2, 2.4.0rc3, 2.4.0rc4, 2.4.0rc5, 2.4.0rc6, 2.4.0rc7, 2.4.1, 2.4.10, 2.4.11, 2.4.2, 2.4.3, 2.4.4, 2.4.5, 2.4.6, 2.4.7, 2.4.8, 2.4.9, 2.5.0, 2.5.1, 2.5.2, 2.6.0, 2.6.1, 2.6.2, 2.6.3, 2.6.x-dev] but these conflict with your requirements or minimum-stability.
    - Installation request for bjyoungblood/bjy-authorize =1.4.0 -> satisfiable by bjyoungblood/bjy-authorize[1.4.0]. `
Can I simply change the dependency for BjyAuthorize? 
Or can I force it?
I need to have zrnd-mvc 3.1 and event_manager ~3.1.0

**Comment by kokspflanze** [comment]
@barry1955 you can use my fork like in https://github.com/bjyoungblood/BjyAuthorize/pull/311 written, maybe that help you with zf3 and that module

**Comment by n0v3xx** [comment]
@kokspflanze thanks for that. Its rly sad that the main project still dead.

**Comment by jarrettj** [comment]
+1 for maintenance

**Comment by lon9man** [comment]
+1 for maintenance

i see in code a bunch deprecated methods and remarks about BjyAuthorize 2.0.x. maybe it is time to make start in the same way as Falcon Heavy? :)

**Comment by jarrettj** [comment]
+1 for maintenance, it's 2018 :)
